#!/usr/bin/env bash

ok=${ printf "\033[0;32m%b\033[0m" "pup:"; }
warn=${ printf "\033[0;33m%b\033[0m" "pup:"; }
bad=${ printf "\033[0;31m%b\033[0m" "pup:"; }

# Looks insane but this is equivalent to 'date +%A'. The -1 asks for a current
# date but to be honest I don't really understand that part. The main thing
# is that %()T lets you put date formatting stuff between the parentheses.
today="${ printf "%(%A)T" "-1"; }"
declare -A upd_days
upd_days=([Friday]=1 [Wednesday]=1)
is_upd_day="false"

# Undefined keys return empty strings 
[[ -n "${upd_days[$today]}" ]] && is_upd_day="true"

if [[ "$is_upd_day" == "true" || "$1" == "--force" ]]; then
    read -rp "${ok} Have you checked for problematic updates? [y/N] " informed
else
    echo "${bad} Update days are set to: ${!upd_days[*]}"
    exit 1
fi

vet() {
    local cmd=("$@") # @ leaves as args, * turns into string

    echo "Updating packages with: ${cmd[*]}"
    "${cmd[@]}" # Runs each argument passed to this function

    local exit_status="${?}"
    if [[ ${exit_status} -ne 0 ]]; then
        echo "${bad} ${cmd[*]} failed with exit status ${exit_status}."
        exit 1
    fi
}

case ${informed,,} in # ${var,,} converts the variable to lowercase
    "y"|"yup"|"yes") 
        vet paru -Syu
        vet flatpak update --user --assumeyes
        vet tldr --update
        echo "${ok} Done!"
        [[ -n $(command -v notify-send) ]] \
            && notify-send "pup" "Updates complete!"
        exit 0
        ;;
    *)
        echo "${warn} No packages were updated. Read the news!"
        echo "${warn} Fetching news..."
        paru -Pw
        exit 1
        ;;
esac
